---
name: dominion
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - tqdm
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - rope
  - pytorch
  # - cpuonly ## enable if no cuda
  - seaborn
  - ipykernel
