---
name: pydominion
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.8.8
  - tqdm
  - numpy
  - pandas
  - scikit-learn=0.23.2
  - matplotlib
  - rope
  - pytorch
  - tensorboard
  # - cpuonly ## enable if no cuda
  - seaborn
  - ipykernel
